Add bucket histogram option
nakabonne/ali pull request #68
Opened 2020-10-14 05:57 UTC by rzkmak

I'm trying to add an option for bucket histogram as in the #63 issue

```
ali --buckets "1ms, 10ms, 100ms, 500ms" http://host.xz
```

But I'm not sure where I can put this part
```
0~1ms: 1 25%
1ms~10ms: 1 25%
10ms~100ms: 1 25%
100ms~500ms: 1 25%
```

Any feedback or revision would help me so much.
Thank you

2020-10-14 12:18 UTC, nakabonne commented
@rzkmak Hey, thank you for your contribution! I can’t afford to check it, so I'll get back to you later :-)

2020-10-17 00:57 UTC, nakabonne requested changes

2020-10-17 00:57 UTC, nakabonne commented on main.go
> +	flagSet.StringVar(&c.buckets, "buckets", "", "Histogram buckets.")
```suggestion
	flagSet.StringVar(&c.buckets, "buckets", "", "Histogram buckets; comma-separated list.")
```

2020-10-17 00:57 UTC, nakabonne commented on main.go
> +			log.Fatalf("Invalid bucket time format")
Can you make it give back an error if even one of them fails?

2020-10-17 00:57 UTC, nakabonne commented on main.go
> +	stringBuckets := strings.Split(rawBuckets, ",")
```suggestion
	stringBuckets := strings.Split(rawBuckets, ",")
	result := make([]time.Duration, len(stringBuckets))

```

2020-10-17 01:55 UTC, rzkmak commented
thank you for the review :+1:

2020-10-17 09:23 UTC, nakabonne approved these changes
thank you! i will add an ability to draw the histogram buckets, so your contribution will be available after that ;)

2020-10-17 09:23 UTC, merged