Fix Progress gauge to reach 100%
nakabonne/ali pull request #86
Opened 2020-11-16 15:13 UTC by shubham14bajpai

Signed-off-by: shubham <shubham.bajpai@mayadata.io>

This PR fixes the stuck progress bar when the rate flag is more than the system capabilities.
![image](https://user-images.githubusercontent.com/16064787/99269262-2a770200-284c-11eb-98dd-2ec2e5cd0d3c.png)

The most accurate representation was on nanoseconds.

2020-11-18 13:06 UTC, nakabonne requested changes

2020-11-18 13:06 UTC, nakabonne commented on gui/drawer.go
> +	totalTime := float64(duration)
I'd say we don't have to do redraw the gauge as soon as a result arrives anymore.

```suggestion
	ticker := time.NewTicker(redrawInterval)
	defer ticker.Stop()

	totalTime := float64(duration)
```

2020-11-18 13:06 UTC, nakabonne commented on gui/drawer.go
>  		case <-d.gaugeCh:
Let's remove the `gaugeCh` field from drawer.

```suggestion
		case <-ticker.C:
```

2020-11-18 13:06 UTC, nakabonne commented on gui/drawer.go
> +				percent = 100
We'd better avoid calling Termdash API more than needed.

```suggestion
				percent = 100
				continue
```

2020-11-18 13:12 UTC, nakabonne commented
@shubham14bajpai Thank you for your contribution! I've left some comments.

>sometimes the progress bar finishes milliseconds before the other sections of the GUI https://github.com/nakabonne/ali/issues/80#issuecomment-728129031

This is caused by entirely another problem with ali's drawing performance. If the ali is running at a high rate, the drawing may not be finished after the specified duration of time. This has been improved considerably, but there is still room for improvement.

2020-11-20 06:30 UTC, shubham14bajpai commented
@nakabonne I have addressed review comments. PTAL.

2020-11-22 06:10 UTC, nakabonne approved these changes
Looks pretty neat. Thanks for your help!

2020-11-22 06:10 UTC, merged